// src/components/dashboard/CardWidget.tsx
'use client';

import { useState, useRef, useEffect, type ReactNode } from 'react';

interface CardWidgetProps {
  info?: string;
  marginBottom?: boolean;
  title: ReactNode;
  children: ReactNode;
}

export function CardWidget({ info, marginBottom = true, title, children }: CardWidgetProps) {
  const [showTooltip, setShowTooltip] = useState(false);
  const tooltipRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (
        showTooltip &&
        tooltipRef.current &&
        buttonRef.current &&
        !tooltipRef.current.contains(e.target as Node) &&
        !buttonRef.current.contains(e.target as Node)
      ) {
        setShowTooltip(false);
      }
    }
    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  }, [showTooltip]);

  return (
    <div
      className={`bg-gray-50 p-6 rounded-xl border-2 relative flex flex-col justify-between ${marginBottom ? 'mb-6' : ''}`}
      style={{
        borderColor: 'var(--color-propolis-teal)',
        minHeight: '180px',
        minWidth: '220px',
        boxShadow: '0 2px 8px 0 rgba(0,0,0,0.03)'
      }}
    >
      <div className="flex justify-between items-start mb-2">
        <div className="text-xs text-gray-500 font-semibold">{title}</div>
        {info && (
          <div className="relative flex items-center ml-2">
            <button
              ref={buttonRef}
              onClick={(e) => { e.stopPropagation(); setShowTooltip((v) => !v); }}
              className="h-5 w-5 flex items-center justify-center text-gray-400 hover:text-yellow-400 cursor-pointer transition-colors"
              aria-label="Show formula"
              aria-expanded={showTooltip}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <circle cx="12" cy="12" r="10" strokeWidth="2" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 16v-4m0-4h.01" />
              </svg>
            </button>
            {showTooltip && (
              <div
                ref={tooltipRef}
                className="absolute left-1/2 top-full z-10 mt-2 w-40 -translate-x-1/2 rounded bg-white p-2 text-xs text-gray-700 shadow-lg"
              >
                {info}
              </div>
            )}
          </div>
        )}
      </div>
      <div className="flex-1 flex flex-col justify-center">{children}</div>
    </div>
  );
}

// src/lib/components/dashboard/CardWidget.svelte
<script lang="ts">
    import { onMount } from 'svelte';

    // Props
    export let marginBottom = true;
    export let info = '';

    // Year-over-year comparison props
    export let prevValueFormatted: string | null = null;
    export let prevLabel: string = '';
    export let changePct: number | null = null;
    export let higherIsBetter: boolean = true;
    export let prevLoading: boolean = false;

    $: showComparison = prevLoading || prevValueFormatted !== null;
    
    // State for tooltip visibility
    let showTooltip = false;
    let tooltipElement: HTMLDivElement;
    let buttonElement: HTMLButtonElement;
    
    function toggleTooltip() {
      showTooltip = !showTooltip;
    }
    
    function closeTooltip() {
      showTooltip = false;
    } 
    
    // Close tooltip when clicking outside
    onMount(() => {
      function handleClickOutside(event: MouseEvent) {
        if (showTooltip && 
            tooltipElement && 
            buttonElement &&
            !tooltipElement.contains(event.target as Node) &&
            !buttonElement.contains(event.target as Node)) {
          closeTooltip();
        }
      }
      
      document.addEventListener('click', handleClickOutside);
      return () => {
        document.removeEventListener('click', handleClickOutside);
      };
    });
</script>
  
  <div class="bg-gray-50 p-6 rounded-xl card-metric {marginBottom ? 'mb-6' : ''} border-2 border-[color:var(--color-propolis-teal)] relative min-h-[180px] flex flex-col justify-between">
    <div class="flex justify-between items-start mb-2">
      <slot name="title"></slot>
      {#if info}
        <div class="relative flex items-center ml-2">
          <button
            bind:this={buttonElement}
            on:click|stopPropagation={toggleTooltip}
            class="h-5 w-5 flex items-center justify-center text-gray-400 hover:text-[color:var(--color-propolis-yellow)] cursor-pointer transition-colors {showTooltip ? 'text-[color:var(--color-propolis-yellow)]' : ''}"
            aria-label="Show formula"
            aria-expanded={showTooltip}
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><circle cx="12" cy="12" r="10" stroke-width="2"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 16v-4m0-4h.01"/></svg>
          </button>
          {#if showTooltip}
            <div 
              bind:this={tooltipElement}
              class="absolute left-1/2 top-full z-10 mt-2 w-40 -translate-x-1/2 rounded bg-white p-2 text-xs text-gray-700 shadow-lg transition-opacity pointer-events-auto"
            >
              {info}
            </div>
          {/if}
        </div>
      {/if}
    </div>
    <div class="flex-1 flex flex-col justify-center">
      <slot></slot>
    </div>

    {#if showComparison}
      <div class="mt-3 pt-2.5 border-t border-gray-200">
        {#if prevLoading && prevValueFormatted === null}
          <div class="flex items-center justify-between gap-2">
            <div class="h-3 w-24 bg-gray-200 rounded animate-pulse"></div>
            <div class="h-4 w-12 bg-gray-200 rounded-full animate-pulse"></div>
          </div>
        {:else if prevValueFormatted !== null}
          <div class="flex items-center justify-between gap-1 flex-wrap">
            <span class="text-xs text-gray-400">
              {prevLabel}: <span class="font-medium text-gray-500">{prevValueFormatted}</span>
            </span>
            {#if changePct !== null}
              {@const isPositive = changePct >= 0}
              {@const isGood = higherIsBetter ? isPositive : !isPositive}
              <span class="text-xs font-semibold px-1.5 py-0.5 rounded-full leading-tight
                {isGood ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-600'}">
                {isPositive ? '+' : ''}{changePct.toFixed(1)}%
              </span>
            {/if}
          </div>
        {/if}
      </div>
    {/if}
  </div>

<style>
  .card-metric {
    min-width: 220px;
    max-width: 100%;
    min-height: 180px;
    box-sizing: border-box;
    /* Subtle shadow and border for propolis accent */
    box-shadow: 0 2px 8px 0 rgba(0,0,0,0.03);
  }
</style>
