// src/lib/components/DashboardSummary.svelte
<script lang="ts">
  import type { DashboardData } from '../types/dashboard';
  import { dashboardLoading, unitFilteringData } from '../stores/simpleDashboardStore';
  import { userRole } from '../api/auth';
	import WelcomeCard from './dashboard/WelcomeCard.svelte';
  import CardWidget from './dashboard/CardWidget.svelte';

  export let dashboardData: DashboardData;

  $: loading = $dashboardLoading;
  $: unitData = $unitFilteringData;
  $: isOwner = $userRole === 'owner';
  
  // Format currency values
  function formatCurrency(value: number): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(value);
  }
  
  // Format percentage values
  function formatPercentage(value: number): string {
    return `${value.toFixed(1)}%`;
  }
  
  // Format large numbers with commas
  function formatNumber(value: number): string {
    return new Intl.NumberFormat('en-US').format(value);
  }
  
</script>

<div class="dashboard-summary">
  
  <WelcomeCard />
  <p class="subtitle">Real-time data from Doorloop (Long-term) and Guesty (Short-term)</p>
  

  
  <!-- Revenue Section -->
  <div class="section">
    <h2>📊 Revenue Overview</h2>
    <div class="cards-grid">
      <CardWidget info="Formula: longterm revenue + shortterm revenue">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">
          {#if unitData}
            Total Revenue (Filtered)
          {:else}
            Total Revenue
          {/if}
        </span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">
          {#if unitData && unitData.filters_applied?.type === 'long-term' && unitData.data.length > 0}
            {formatCurrency(unitData.data.reduce((sum, item) => sum + (item.Revenue || 0), 0))}
          {:else if unitData && unitData.filters_applied?.type === 'short-term' && unitData.data.length > 0}
            {formatCurrency(unitData.data.reduce((sum, item) => sum + (item.Revenue || 0), 0))}
          {:else}
            {formatCurrency(dashboardData.totalRevenue)}
          {/if}
        </div>
        {#if unitData}
          <div class="text-xs text-gray-500 mt-1">
            {unitData.filters_applied.property} - {unitData.filters_applied.unit}
          </div>
        {/if}
      </CardWidget>
      <CardWidget info="Cash basis: counts rent the month the payment was received. Matches DoorLoop's P&L and typical owner reporting.">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">
          {#if unitData && unitData.filters_applied?.type === 'long-term'}
            Long Term Revenue (Filtered)
          {:else}
            Long Term Revenue{#if isOwner} <span class="rounded bg-teal-50 px-1.5 py-0.5 text-[10px] font-medium text-teal-700">Cash</span>{/if}
          {/if}
        </span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">
          {#if unitData && unitData.filters_applied?.type === 'long-term' && unitData.data.length > 0}
            {formatCurrency(unitData.data.reduce((sum, item) => sum + (item.Revenue || 0), 0))}
          {:else if unitData && unitData.filters_applied?.type === 'short-term'}
            {formatCurrency(0)}
          {:else}
            {formatCurrency(dashboardData.longTermRevenue)}
          {/if}
        </div>
        {#if unitData && unitData.filters_applied?.type === 'long-term'}
          <div class="text-xs text-gray-500 mt-1">
            {unitData.filters_applied.property} - {unitData.filters_applied.unit}
          </div>
        {/if}
      </CardWidget>
      {#if isOwner && dashboardData.longTermRevenueAccrual != null && (!unitData || !unitData.filters_applied)}
        <CardWidget info="Accrual basis: counts rent in the month it was earned, regardless of when it was paid. Owner view only.">
          <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">
            Long Term Revenue <span class="rounded bg-purple-50 px-1.5 py-0.5 text-[10px] font-medium text-purple-700">Accrual</span>
          </span>
          <div class="card-value text-2xl font-bold text-purple-700">
            {formatCurrency(dashboardData.longTermRevenueAccrual)}
          </div>
        </CardWidget>
      {/if}
      <CardWidget info="Formula: Short term gross income">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">
          {#if unitData && unitData.filters_applied?.type === 'short-term'}
            Short Term Revenue (Filtered)
          {:else}
            Short Term Revenue
          {/if}
        </span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">
          {#if unitData && unitData.filters_applied?.type === 'short-term' && unitData.data.length > 0}
            {formatCurrency(unitData.data.reduce((sum, item) => sum + (item.Revenue || 0), 0))}
          {:else}
            {formatCurrency(dashboardData.shortTermRevenue)}
          {/if}
        </div>
        {#if unitData && unitData.filters_applied?.type === 'short-term'}
          <div class="text-xs text-gray-500 mt-1">
            {unitData.filters_applied.property} - {unitData.filters_applied.unit}
          </div>
        {/if}
      </CardWidget>
     
    </div>
  </div>
  
  <!-- Occupancy Section -->
  <div class="section">
    <h2>🏠 Occupancy Rates</h2>
    <div class="cards-grid">
      <CardWidget info="Formula: longterm occupancy + shortterm occupancy / 2">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Average Occupancy</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">{formatPercentage(dashboardData.averageOccupancyRate)}</div>
       
      </CardWidget>
      <CardWidget info="Binary: any active lease in the period counts as 100% occupied. Matches DoorLoop's UI.">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">
          Long-term Occupancy{#if isOwner} <span class="rounded bg-teal-50 px-1.5 py-0.5 text-[10px] font-medium text-teal-700">Binary</span>{/if}
        </span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">{formatPercentage(dashboardData.longTermOccupancyRate)}</div>
      </CardWidget>
      {#if isOwner && dashboardData.longTermOccupancyRateProrated != null}
        <CardWidget info="Prorated: days of lease coverage ÷ days in period. Reflects mid-month move-ins/outs. Owner view only.">
          <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">
            Long-term Occupancy <span class="rounded bg-purple-50 px-1.5 py-0.5 text-[10px] font-medium text-purple-700">Prorated</span>
          </span>
          <div class="card-value text-2xl font-bold text-purple-700">{formatPercentage(dashboardData.longTermOccupancyRateProrated)}</div>
        </CardWidget>
      {/if}
      <CardWidget info="Formula: total occupied units / total units ">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Short-term Occupancy</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-yellow)]">{formatPercentage(dashboardData.shortTermOccupancyRate)}</div>
        
      </CardWidget>
    </div>
  </div>
  
  <!-- Additional Metrics -->
  <div class="section">
    <h2>📈 Additional Metrics</h2>
    <div class="cards-grid four-column">
      <CardWidget info="Formula: ( Σ (Lease End Date – Lease Start Date) ) ÷ (Number of Leases)">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Avg Lease Tenancy</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">{dashboardData.averageLeaseTenancy} days</div>
      </CardWidget>
      <CardWidget info="Formula: Σ (Lease Start Date – Vacancy Date) ) ÷ (Number of Leases Signed)">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Time to Lease</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">{dashboardData.timeToLease} days</div>
      </CardWidget>
      <CardWidget info="Formula: (Move-Outs ÷ Active Tenants) × 100">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Tenant Turnover</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-yellow)]">{formatPercentage(dashboardData.tenantTurnover)}</div>
      </CardWidget>
      <CardWidget info="Formula: Total STR Revenue ÷ Nights Booked">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Avg Daily Rate</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-yellow)]">{formatCurrency(dashboardData.shortTermAverageDailyRate)}</div>
      </CardWidget>
      <CardWidget info="Formula: Total STR Revenue ÷ Available Nights">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Revenue per Available Room</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-teal)]">{formatCurrency(dashboardData.revenuePerAvailableRoom)}</div>
      </CardWidget>
      <CardWidget info="Formula: Total Charges - Total Amount Paid">
        <span slot="title" class="mb-1 text-xs text-gray-500 font-semibold">Balance Overdue</span>
        <div class="card-value text-2xl font-bold text-[color:var(--color-propolis-yellow)]">{formatCurrency(dashboardData.leaseBalanceOverdue)}</div>
      </CardWidget>
    </div>
  </div>
</div>

<style>
  .dashboard-summary {
    padding: 0rem;
    max-width: 1400px;
    margin: 0 auto;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  }
  
  .subtitle {
    color: #6b7280;
    font-size: 1.1rem;
    margin: 0 0 2rem 0;
  }
  
  .section {
    margin-bottom: 3rem;
  }
  
  h2 {
    font-size: 1.5rem;
    font-weight: 600;
    color: #374151;
    margin: 0 0 1.5rem 0;
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }
  .cards-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 1.5rem;
  }
  .cards-grid.four-column {
    grid-template-columns: repeat(3, 1fr);
  }
  

  
  @media (max-width: 900px) {
    .cards-grid, .cards-grid.four-column {
      grid-template-columns: 1fr;
    }
  }
 
  
  .card-value {
    font-size: 2rem;
    font-weight: 700;
    color: #1f2937;
    margin-bottom: 0.5rem;
  }
  
 
  
  @media (max-width: 768px) {
    .dashboard-summary {
      padding: 1rem;
    }
    

    
    .cards-grid {
      grid-template-columns: 1fr;
    }
    
    .cards-grid.four-column {
      grid-template-columns: repeat(2, 1fr);
    }
  }
</style>

// src/components/DashboardSummary.tsx
'use client';

import type { DashboardData } from '@/lib/types/dashboard';
import { useDashboardStore } from '@/stores/dashboardStore';
import { useAuthStore } from '@/stores/authStore';
import { WelcomeCard } from './dashboard/WelcomeCard';
import { CardWidget } from './dashboard/CardWidget';

function formatCurrency(value: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
}

function formatPercentage(value: number) {
  return `${value.toFixed(1)}%`;
}

interface Props {
  dashboardData: DashboardData;
}

export function DashboardSummary({ dashboardData }: Props) {
  const unitData = useDashboardStore((s) => s.unitFilteringData);
  const user = useAuthStore((s) => s.user);
  const isOwner = user?.role === 'owner';

  const ltRevFromUnit =
    unitData?.filters_applied?.type === 'long-term' && unitData.data.length > 0
      ? unitData.data.reduce((sum, item) => sum + ((item as Record<string, number>).Revenue || 0), 0)
      : null;

  const stRevFromUnit =
    unitData?.filters_applied?.type === 'short-term' && unitData.data.length > 0
      ? unitData.data.reduce((sum, item) => sum + ((item as Record<string, number>).Revenue || 0), 0)
      : null;

  return (
    <div className="max-w-[1400px] mx-auto" style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }}>
      <WelcomeCard />
      <p className="text-gray-500 text-lg mb-8">Real-time data from Doorloop (Long-term) and Guesty (Short-term)</p>

      {/* Revenue */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold text-gray-700 mb-6 flex items-center gap-2">📊 Revenue Overview</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <CardWidget info="Formula: longterm revenue + shortterm revenue" title={unitData ? 'Total Revenue (Filtered)' : 'Total Revenue'}>
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>
              {formatCurrency(
                ltRevFromUnit != null ? ltRevFromUnit : stRevFromUnit != null ? stRevFromUnit : dashboardData.totalRevenue
              )}
            </div>
            {unitData && (
              <div className="text-xs text-gray-500 mt-1">{unitData.filters_applied.property} - {unitData.filters_applied.unit}</div>
            )}
          </CardWidget>

          <CardWidget
            info="Cash basis: counts rent the month the payment was received."
            title={
              unitData?.filters_applied?.type === 'long-term'
                ? 'Long Term Revenue (Filtered)'
                : isOwner
                ? <span>Long Term Revenue <span className="rounded bg-teal-50 px-1.5 py-0.5 text-[10px] font-medium text-teal-700">Cash</span></span>
                : 'Long Term Revenue'
            }
          >
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>
              {formatCurrency(
                ltRevFromUnit != null ? ltRevFromUnit : unitData?.filters_applied?.type === 'short-term' ? 0 : dashboardData.longTermRevenue
              )}
            </div>
            {unitData?.filters_applied?.type === 'long-term' && (
              <div className="text-xs text-gray-500 mt-1">{unitData.filters_applied.property} - {unitData.filters_applied.unit}</div>
            )}
          </CardWidget>

          {isOwner && dashboardData.longTermRevenueAccrual != null && !unitData && (
            <CardWidget
              info="Accrual basis: counts rent in the month it was earned."
              title={<span>Long Term Revenue <span className="rounded bg-purple-50 px-1.5 py-0.5 text-[10px] font-medium text-purple-700">Accrual</span></span>}
            >
              <div className="text-2xl font-bold text-purple-700">
                {formatCurrency(dashboardData.longTermRevenueAccrual)}
              </div>
            </CardWidget>
          )}

          <CardWidget
            info="Formula: Short term gross income"
            title={unitData?.filters_applied?.type === 'short-term' ? 'Short Term Revenue (Filtered)' : 'Short Term Revenue'}
          >
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>
              {formatCurrency(stRevFromUnit != null ? stRevFromUnit : dashboardData.shortTermRevenue)}
            </div>
            {unitData?.filters_applied?.type === 'short-term' && (
              <div className="text-xs text-gray-500 mt-1">{unitData.filters_applied.property} - {unitData.filters_applied.unit}</div>
            )}
          </CardWidget>
        </div>
      </div>

      {/* Occupancy */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold text-gray-700 mb-6 flex items-center gap-2">🏠 Occupancy Rates</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <CardWidget info="Formula: longterm occupancy + shortterm occupancy / 2" title="Average Occupancy">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>{formatPercentage(dashboardData.averageOccupancyRate)}</div>
          </CardWidget>
          <CardWidget
            info="Binary: any active lease in the period counts as 100% occupied."
            title={isOwner ? <span>Long-term Occupancy <span className="rounded bg-teal-50 px-1.5 py-0.5 text-[10px] font-medium text-teal-700">Binary</span></span> : 'Long-term Occupancy'}
          >
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>{formatPercentage(dashboardData.longTermOccupancyRate)}</div>
          </CardWidget>
          {isOwner && dashboardData.longTermOccupancyRateProrated != null && (
            <CardWidget
              info="Prorated: days of lease coverage ÷ days in period."
              title={<span>Long-term Occupancy <span className="rounded bg-purple-50 px-1.5 py-0.5 text-[10px] font-medium text-purple-700">Prorated</span></span>}
            >
              <div className="text-2xl font-bold text-purple-700">{formatPercentage(dashboardData.longTermOccupancyRateProrated)}</div>
            </CardWidget>
          )}
          <CardWidget info="Formula: total occupied units / total units" title="Short-term Occupancy">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-yellow)' }}>{formatPercentage(dashboardData.shortTermOccupancyRate)}</div>
          </CardWidget>
        </div>
      </div>

      {/* Additional Metrics */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold text-gray-700 mb-6 flex items-center gap-2">📈 Additional Metrics</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <CardWidget info="Formula: ( Σ (Lease End Date – Lease Start Date) ) ÷ (Number of Leases)" title="Avg Lease Tenancy">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>{dashboardData.averageLeaseTenancy} days</div>
          </CardWidget>
          <CardWidget info="Formula: Σ (Lease Start Date – Vacancy Date) ) ÷ (Number of Leases Signed)" title="Time to Lease">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>{dashboardData.timeToLease} days</div>
          </CardWidget>
          <CardWidget info="Formula: (Move-Outs ÷ Active Tenants) × 100" title="Tenant Turnover">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-yellow)' }}>{formatPercentage(dashboardData.tenantTurnover)}</div>
          </CardWidget>
          <CardWidget info="Formula: Total STR Revenue ÷ Nights Booked" title="Avg Daily Rate">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-yellow)' }}>{formatCurrency(dashboardData.shortTermAverageDailyRate)}</div>
          </CardWidget>
          <CardWidget info="Formula: Total STR Revenue ÷ Available Nights" title="Revenue per Available Room">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-teal)' }}>{formatCurrency(dashboardData.revenuePerAvailableRoom)}</div>
          </CardWidget>
          <CardWidget info="Formula: Total Charges - Total Amount Paid" title="Balance Overdue">
            <div className="text-2xl font-bold" style={{ color: 'var(--color-propolis-yellow)' }}>{formatCurrency(dashboardData.leaseBalanceOverdue)}</div>
          </CardWidget>
        </div>
      </div>
    </div>
  );
}
