// src/lib/components/dashboard/WelcomeCard.svelte
<script lang="ts">
	import { Mic, Sparkles, Filter } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { dashboardDateRange, updateDateRange, refetchDashboardData, appliedDateRange } from '../../stores/simpleDashboardStore';
	import AIView from './AIView.svelte';
	import PropertyDropdown from '../PropertyDropdown.svelte';
	import UnitsDropdown from '../UnitsDropdown.svelte';
	
	let day = 19;
	let dayOfWeek = 'Tue';
	let month = 'December';
	let year = '2025';
	
	// Date range variables
	let startDate = '';
	let endDate = '';
	
	// AI View state
	let isAIViewOpen = false;
	
	onMount(() => {
		const now = new Date();
		day = now.getDate();
		dayOfWeek = now.toLocaleDateString('en-US', { weekday: 'long' });
		month = now.toLocaleDateString('en-US', { month: 'long' });
		year = now.toLocaleDateString('en-us', { year: 'numeric' });
		
		// Initialize date range from store
		const unsubscribe = dashboardDateRange.subscribe(dateRange => {
			startDate = dateRange.startDate;
			endDate = dateRange.endDate;
		});
		unsubscribe();
	});
	
	function toggleAIView() {
		isAIViewOpen = !isAIViewOpen;
	}
	
	// Apply filters when filter button is clicked
	function applyFilters() {
		if (startDate && endDate) {
			const range = { startDate, endDate };
			updateDateRange(range);
			appliedDateRange.set(range);
		} else {
			refetchDashboardData();
			appliedDateRange.set(null);
		}
	}
	
	// Quick date range presets (only set dates, don't filter)
	function setQuickRange(days: number) {
		const today = new Date();
		const start = new Date(today);
		start.setDate(today.getDate() - days);
		
		startDate = start.toISOString().split('T')[0];
		endDate = today.toISOString().split('T')[0];
		// Don't auto-filter, user must click filter button
	}
	
	function setCurrentMonth() {
		const now = new Date();
		const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
		const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);
		
		startDate = startOfMonth.toISOString().split('T')[0];
		endDate = endOfMonth.toISOString().split('T')[0];
		// Don't auto-filter, user must click filter button
	}
</script>

<!-- Date Header Section with Inline Filters -->
<div class="mb-8">
	<!-- Main row with date, AI button, and filters -->
	<div class="flex items-center justify-between w-full gap-4">
		<!-- Date Section -->
		<div class="flex items-center gap-4">
			<div class="flex h-24 w-24 flex-col items-center justify-center rounded-full border border-gray-200">
				<div class="text-4xl font-semibold">{day}</div>
			</div>
			<div>
				<div class="text-xl font-medium text-gray-600">{dayOfWeek},</div>
				<div class="text-2xl font-bold text-gray-800">{month} {year}</div>
			</div>
		</div>

		<!-- Filters + AI Section -->
		<div class="flex items-end gap-6">
			<!-- Date Range Filter -->
			<div class="flex flex-col gap-2">
				<div class="text-sm font-medium text-slate-700">Date Range</div>
				<div class="flex gap-2">
					<input
						type="date"
						bind:value={startDate}
						class="focus:ring-coral-500 rounded-lg border border-slate-300 bg-white py-2 px-3 text-sm text-slate-700 transition-all focus:border-transparent focus:ring-2"
						placeholder="Start Date"
					/>
					<input
						type="date"
						bind:value={endDate}
						class="focus:ring-coral-500 rounded-lg border border-slate-300 bg-white py-2 px-3 text-sm text-slate-700 transition-all focus:border-transparent focus:ring-2"
						placeholder="End Date"
					/>
				</div>
			</div>

			<!-- Property Filter -->
			<div class="flex flex-col gap-2">
				<div class="text-sm font-medium text-slate-700">Property Filter</div>
				<PropertyDropdown />
			</div>

			<!-- Units Filter -->
			<div class="flex flex-col gap-2">
				<div class="text-sm font-medium text-slate-700">Units Filter</div>
				<UnitsDropdown />
			</div>

			<!-- Filter Button -->
			<div class="flex flex-col gap-2">
				<div class="text-sm font-medium text-slate-700 opacity-0">Apply</div>
				<button
					on:click={applyFilters}
					class="flex items-center gap-2 px-4 py-2 text-white rounded-lg transition-colors font-medium text-sm"
					style="background-color: var(--color-propolis-teal);"
					on:mouseenter={(e) => e.currentTarget.style.opacity = '0.9'}
					on:mouseleave={(e) => e.currentTarget.style.opacity = '1'}
				>
					<Filter class="w-4 h-4" />
					Apply Filters
				</button>
			</div>

			<!-- AI Button (aligned with Apply Filters) -->
			<div class="flex flex-col gap-2">
				<div class="text-sm font-medium text-slate-700 opacity-0">AI</div>
				<button
					on:click={() => isAIViewOpen = true}
					class="relative cursor-pointer hover:scale-105 transition-transform duration-200"
				>
					<div class="absolute inset-0 rounded-2xl animate-pulse" style="background: linear-gradient(135deg, var(--color-propolis-teal), var(--color-propolis-yellow))"></div>
					<div class="relative flex items-center justify-center w-10 h-10 rounded-2xl shadow-lg" style="background: linear-gradient(135deg, var(--color-propolis-teal), var(--color-propolis-yellow))">
						<Sparkles class="w-5 h-5 text-white animate-bounce" />
					</div>
				</button>
			</div>
		</div>
	</div>

	<!-- Quick preset buttons row -->
	<div class="flex gap-1 mt-3">
		<button
			on:click={() => setQuickRange(7)}
			class="px-2 py-1 text-xs bg-slate-100 hover:bg-slate-200 rounded transition-colors"
		>
			7 Days
		</button>
		<button
			on:click={() => setQuickRange(30)}
			class="px-2 py-1 text-xs bg-slate-100 hover:bg-slate-200 rounded transition-colors"
		>
			30 Days
		</button>
		<button
			on:click={setCurrentMonth}
			class="px-2 py-1 text-xs bg-slate-100 hover:bg-slate-200 rounded transition-colors"
		>
			This Month
		</button>
	</div>
</div>

<!-- AI View -->
<AIView bind:isOpen={isAIViewOpen} />

// src/components/dashboard/WelcomeCard.tsx
'use client';

import { useState, useEffect } from 'react';
import { Filter, Sparkles } from 'lucide-react';
import { useDashboardStore } from '@/stores/dashboardStore';
import { PropertyDropdown } from '@/components/PropertyDropdown';
import { UnitsDropdown } from '@/components/UnitsDropdown';

export function WelcomeCard() {
  const [day, setDay] = useState('');
  const [dayOfWeek, setDayOfWeek] = useState('');
  const [month, setMonth] = useState('');
  const [year, setYear] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const { dateRange, updateDateRange, fetchDashboardData } = useDashboardStore();

  useEffect(() => {
    const now = new Date();
    setDay(String(now.getDate()));
    setDayOfWeek(now.toLocaleDateString('en-US', { weekday: 'long' }));
    setMonth(now.toLocaleDateString('en-US', { month: 'long' }));
    setYear(now.toLocaleDateString('en-US', { year: 'numeric' }));
    setStartDate(dateRange.startDate);
    setEndDate(dateRange.endDate);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  function applyFilters() {
    if (startDate && endDate) {
      updateDateRange({ startDate, endDate });
    } else {
      fetchDashboardData();
    }
  }

  function setQuickRange(days: number) {
    const today = new Date();
    const start = new Date(today);
    start.setDate(today.getDate() - days);
    setStartDate(start.toISOString().split('T')[0]);
    setEndDate(today.toISOString().split('T')[0]);
  }

  function setCurrentMonth() {
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    setStartDate(startOfMonth.toISOString().split('T')[0]);
    setEndDate(endOfMonth.toISOString().split('T')[0]);
  }

  return (
    <div className="mb-8">
      <div className="flex items-center justify-between w-full gap-4">
        <div className="flex items-center gap-4">
          <div className="flex h-24 w-24 flex-col items-center justify-center rounded-full border border-gray-200">
            <div className="text-4xl font-semibold">{day}</div>
          </div>
          <div>
            <div className="text-xl font-medium text-gray-600">{dayOfWeek},</div>
            <div className="text-2xl font-bold text-gray-800">{month} {year}</div>
          </div>
        </div>

        <div className="flex items-end gap-6 flex-wrap">
          <div className="flex flex-col gap-2">
            <div className="text-sm font-medium text-slate-700">Date Range</div>
            <div className="flex gap-2">
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="rounded-lg border border-slate-300 bg-white py-2 px-3 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-transparent"
              />
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="rounded-lg border border-slate-300 bg-white py-2 px-3 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-transparent"
              />
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <div className="text-sm font-medium text-slate-700">Property Filter</div>
            <PropertyDropdown />
          </div>

          <div className="flex flex-col gap-2">
            <div className="text-sm font-medium text-slate-700">Units Filter</div>
            <UnitsDropdown />
          </div>

          <div className="flex flex-col gap-2">
            <div className="text-sm font-medium text-slate-700 opacity-0">Apply</div>
            <button
              onClick={applyFilters}
              className="flex items-center gap-2 px-4 py-2 text-white rounded-lg font-medium text-sm transition-opacity hover:opacity-90"
              style={{ backgroundColor: 'var(--color-propolis-teal)' }}
            >
              <Filter className="w-4 h-4" />
              Apply Filters
            </button>
          </div>

          <div className="flex flex-col gap-2">
            <div className="text-sm font-medium text-slate-700 opacity-0">AI</div>
            <button className="relative cursor-pointer hover:scale-105 transition-transform duration-200">
              <div
                className="absolute inset-0 rounded-2xl animate-pulse"
                style={{ background: 'linear-gradient(135deg, var(--color-propolis-teal), var(--color-propolis-yellow))' }}
              />
              <div
                className="relative flex items-center justify-center w-10 h-10 rounded-2xl shadow-lg"
                style={{ background: 'linear-gradient(135deg, var(--color-propolis-teal), var(--color-propolis-yellow))' }}
              >
                <Sparkles className="w-5 h-5 text-white animate-bounce" />
              </div>
            </button>
          </div>
        </div>
      </div>

      <div className="flex gap-1 mt-3">
        {[7, 30].map((d) => (
          <button
            key={d}
            onClick={() => setQuickRange(d)}
            className="px-2 py-1 text-xs bg-slate-100 hover:bg-slate-200 rounded transition-colors"
          >
            {d} Days
          </button>
        ))}
        <button
          onClick={setCurrentMonth}
          className="px-2 py-1 text-xs bg-slate-100 hover:bg-slate-200 rounded transition-colors"
        >
          This Month
        </button>
      </div>
    </div>
  );
}
