// src/lib/components/ui/Skeleton.svelte
<script lang="ts">
	export let height = '1rem';
	export let width: string = '100%';
	export let rounded: 'sm' | 'md' | 'lg' | 'full' = 'md';
</script>

<div
	class="animate-pulse bg-gray-200"
	class:rounded-sm={rounded === 'sm'}
	class:rounded-md={rounded === 'md'}
	class:rounded-lg={rounded === 'lg'}
	class:rounded-full={rounded === 'full'}
	style="height: {height}; width: {width};"
></div>

// src/components/ui/Skeleton.tsx
'use client';

interface SkeletonProps {
  height?: string;
  width?: string;
  rounded?: string;
  className?: string;
}

export function Skeleton({ height = '1rem', width = '100%', rounded = 'md', className = '' }: SkeletonProps) {
  return (
    <div
      className={`animate-pulse bg-gray-200 rounded-${rounded} ${className}`}
      style={{ height, width }}
    />
  );
}
